---
runner:
  brakeman:
    cmd: bin/brakeman
    level: info
  fasterer:
    cmd: bin/fasterer
    level: info
  reek:
    cmd: bin/reek
    level: info
  rubocop:
    cmd: bin/rubocop
    level: info
