---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/ExampleLength:
  # default is 5
  Max: 10
