---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/**/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/ExampleLength:
  # default is 5
  Max: 10
