---
name: Specs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

      - name: Archive screenshots for failed tests
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-failed-screenshots
          path: spec/dummy/tmp/screenshots
